### ISSUE TITLE
Support `no_std`

### ISSUE THREAD

**Issue by JulianSchmid** [JulianSchmid/etherparse#58]

**Comment by iamwwc** [comment]
When the v0.14 will be release?

**Comment by JulianSchmid** [comment]
> When the v0.14 will be release?

Probably in around ~ 2 weeks.

**Comment by iamwwc** [comment]
could you release the v1.13.1 for no_std support ?

**Comment by JulianSchmid** [comment]
Hi @iamwwc,

I assume you are asking if I could do a pre-release of the current state, which has `no-std` support. I will not do an official release before https://github.com/JulianSchmid/etherparse/issues/46 & https://github.com/JulianSchmid/etherparse/issues/35 are done, but you can also use the current repository state by pointing to it in your `Cargo.toml`:

```toml
[dependencies]
etherpare = { git = "https://github.com/JulianSchmid/etherparse.git", rev = "c33f1b856c3cc32aca5028396dea0c584fdb2be7" }
```

Greets
Julian
